### PR TITLE
Adding Twilight Forest crops to Agricraft

### PR DESCRIPTION
**Pull request by merdink**
Adding JSON files to allow the Twilight Forest crops that are under Mystical Agriculture (Fiery Ingot, Ironwood, Knightmetal, Steeleaf) to be planted in Agricraft crop sticks.

### CODE REVIEW

**Comment by sibomots** [comment]
In what way was this tested?  Just locally?

**Comment by merdink** [comment]
Yes, just locally.

**Comment by sibomots** [comment]
Ok so at the present time, the configuration files in the repo are not **the configuration files** in the server environment.  I will need to make process to pull current the repo's config into the server config.   Not a big deal, but a chore to do manually.  It separates the repo from the server.  In other words, there is no way to actually affect the server with changes to the repo unless the repo is copied into the server's config.   I am going to stitch something up to make that easier, but the firewall will still remain.  After the hack it'll just be a matter of "pulling current" the repo and the server will enjoy the change.    More on this later... Go ahead and merge...    When we get more support (more people involved) we can be a little more formal about PRs, but for the time being, go ahead and merge it.. I'll look at the server update this evening.

**Comment by sibomots** [comment]
What I should do is make a "Mod pack Dev Kit" which is a kit (in the repo) that one can use to unit-test the config with a server environment.  I'll see about that too.

**Pull request merged**
